const char *html_resp =
	"<html>\n"
	"<head>\n"
	"<meta http-equiv=\"content-type\" content=\"text/html; charset=ISO-8859-1\">\n"
	"<title>\n"
	"Armitage</title>\n"
	"<style>\n"
	"body,td,a,p,.h{font-family:arial,sans-serif}.h{font-size:20px}.h{color:#3366cc}.q{color:#00c}.ts td{padding:0}.ts{border-collapse:collapse}#gbar{float:left;font-weight:bold;height:22px;padding-left:2px}.gbh,.gb2 div{border-top:1px solid #c9d7f1;font-size:0;height:0}.gbh{position:absolute;top:24px;width:100%}.gb2 div{margin:5px}#gbi{background:#fff;border:1px solid;border-color:#c9d7f1 #36c #36c #a2bae7;font-size:13px;top:24px;z-index:1000}#guser{padding-bottom:7px !important}#gbar,#guser{font-size:13px;padding-top:1px !important}@media all{.gb1,.gb3{height:22px;margin-right:.73em;vertical-align:top}.gb2 a{display:block;padding:.2em .5em}}#gbi,.gb2{display:none;position:absolute;width:8em}.gb2{z-index:1001}#gbar a,#gbar a:active,#gbar a:visited{color:#00c;font-weight:normal}.gb2 a,.gb3 a{text-decoration:none}#gbar .gb2 a:hover{background:#36c;color:#fff;display:block}</style>\n"
	"<script>\n"
	"window.google={kEI:\"h5e4R9f7EJaywAGyhsXaCg\",kEXPI:\"17870,17984\",kHL:\"en\"};\n"
	"function sf(){document.f.q.focus()}\n"
	"window.gbar={};(function(){var a=window.gbar,b,g,h;function l(c,f,e){c.display=h?\"none\":\"block\";c.left=f+\"px\";c.top=e+\"px\"}a.tg=function(c){var f=0,e=0,d,m=0,n,j=window.navExtra,k,i=document;g=g||i.getElementById(\"gbar\").getElementsByTagName(\"span\");(c||window.event).cancelBubble=!m;if(!b){b=i.createElement(Array.every||window.createPopup?\"iframe\":\"DIV\");b.frameBorder=\"0\";b.scrolling=\"no\";b.src=\"#\";g[7].parentNode.appendChild(b).id=\"gbi\";if(j&&g[7])for(n in j){k=i.createElement(\"span\");k.appendChild(j[n]);g[7].parentNode.insertBefore(k,g[7]).className=\"gb2\"}i.onclick=a.close}while(d=g[++m]){if(e){l(d.style,e+1,f+25);f+=d.firstChild.tagName==\"DIV\"?9:20}if(d.className==\"gb3\"){do e+=d.offsetLeft;while(d=d.offsetParent)}}b.style.height=f+\"px\";l(b.style,e,24);h=!h};a.close=function(c){h&&a.tg(c)}})();</script>\n"
	"</head>\n"
	"<body bgcolor=#ffffff text=#000000 link=#0000cc vlink=#551a8b alink=#ff0000 onload=\"sf();if(document.images){new Image().src='/images/nav_logo3.png'}\" topmargin=3 marginheight=3>\n"
	"<div id=gbar>\n"
	"<nobr>\n"
	"<span class=gb1>\n"
	"Web</a>\n"
	"</span>\n"
	" <span class=gb1>\n"
	"<a href=\"http://images.rmitage.org.uk/imghp?hl=en&tab=wi\">\n"
	"Images</a>\n"
	"</span>\n"
	" <span class=gb1>\n"
	"<a href=\"http://maps.rmitage.org.uk/maps?hl=en&tab=wl\">\n"
	"Maps</a>\n"
	"</span>\n"
	" <span class=gb1>\n"
	"<a href=\"http://news.rmitage.org.uk/nwshp?hl=en&tab=wn\">\n"
	"News</a>\n"
	"</span>\n"
	" <span class=gb1>\n"
	"<a href=\"http://www.rmitage.org.uk/prdhp?hl=en&tab=wf\">\n"
	"Shopping</a>\n"
	"</span>\n"
	" <span class=gb1>\n"
	"<a href=\"http://mail.rmitage.org.uk/mail/?hl=en&tab=wm\">\n"
	"Mail</a>\n"
	"</span>\n"
	" <span class=gb3>\n"
	"<a href=\"http://www.rmitage.org.uk/intl/en/options/\" onclick=\"this.blur();gbar.tg(event);return !1\">\n"
	"<u>\n"
	"more</u>\n"
	" <small>\n"
	"&#9660;</small>\n"
	"</a>\n"
	"</span>\n"
	" <span class=gb2>\n"
	"<a href=\"http://video.rmitage.org.uk/?hl=en&tab=wv\">\n"
	"Video</a>\n"
	"</span>\n"
	" <span class=gb2>\n"
	"<a href=\"http://groups.rmitage.org.uk/grphp?hl=en&tab=wg\">\n"
	"Groups</a>\n"
	"</span>\n"
	" <span class=gb2>\n"
	"<a href=\"http://books.rmitage.org.uk/bkshp?hl=en&tab=wp\">\n"
	"Books</a>\n"
	"</span>\n"
	" <span class=gb2>\n"
	"<a href=\"http://scholar.rmitage.org.uk/schhp?hl=en&tab=ws\">\n"
	"Scholar</a>\n"
	"</span>\n"
	" <span class=gb2>\n"
	"<a href=\"http://blogsearch.rmitage.org.uk/?hl=en&tab=wb\">\n"
	"Blogs</a>\n"
	"</span>\n"
	" <span class=gb2>\n"
	"<div>\n"
	"</div>\n"
	"</a>\n"
	"</span>\n"
	" <span class=gb2>\n"
	"<a href=\"http://www.rmitage.org.uk/calendar/render?hl=en&tab=wc\">\n"
	"Calendar</a>\n"
	"</span>\n"
	" <span class=gb2>\n"
	"<a href=\"http://picasaweb.rmitage.org.uk/home?hl=en&tab=wq\">\n"
	"Photos</a>\n"
	"</span>\n"
	" <span class=gb2>\n"
	"<a href=\"http://docs.rmitage.org.uk/?hl=en&tab=wo\">\n"
	"Documents</a>\n"
	"</span>\n"
	" <span class=gb2>\n"
	"<a href=\"http://www.rmitage.org.uk/reader/view/?hl=en&tab=wy\">\n"
	"Reader</a>\n"
	"</span>\n"
	" <span class=gb2>\n"
	"<div>\n"
	"</div>\n"
	"</a>\n"
	"</span>\n"
	" <span class=gb2>\n"
	"<a href=\"http://www.rmitage.org.uk/intl/en/options/\">\n"
	"even more &raquo;</a>\n"
	"</span>\n"
	" </nobr>\n"
	"</div>\n"
	"<div class=gbh style=left:0>\n"
	"</div>\n"
	"<div class=gbh style=right:0>\n"
	"</div>\n"
	"<div align=right id=guser style=\"font-size:84%;padding:0 0 4px\" width=100%>\n"
	"<nobr>\n"
	"<a href=\"/url?sa=p&pref=ig&pval=3&q=http://www.rmitage.org.uk/ig%3Fhl%3Den%26source%3Diglk&usg=AFQjCNH9dUJQAsNWnO3XKq2EIPgFbczqlA\">\n"
	"iArmitage</a>\n"
	" | <a href=\"https://www.rmitage.org.uk/accounts/Login?continue=http://www.rmitage.org.uk/&hl=en\">\n"
	"Sign in</a>\n"
	"</nobr>\n"
	"</div>\n"
	"<a href=\"https://gnu.org/gnu30\"><img src=\"https://static.fsf.org/nosvn/misc/GNU_30th_badge.png\" align=\"right\" alt=\"[ Celebrate 30 years of GNU! ]\" /></a>\n"
	"<script id=\"fedora-banner\" type=\"text/javascript\" src=\"http://fedoraproject.org/static/js/release-counter-ext.js?lang=en\"></script>\n"
	"<font size=-1>\n"
	"<a href=\"http://uid0.com/ip6dc/armitage.org.uk\">\n"
	"IPv6 status</a>\n"
	"<center>\n"
	"<br clear=all id=lgpd>\n"
	"<img alt=\"Milnesbridge House\" height=136 src=\"/images/cs351.jpg\" width=200>\n"
	"<br>\n"
	"<br>\n"
	"<form action=\"/search\" name=f>\n"
	"<table cellpadding=0 cellspacing=0>\n"
	"<tr valign=top>\n"
	"<td width=25%>\n"
	"&nbsp;</td>\n"
	"<td align=center nowrap>\n"
	"<input name=hl type=hidden value=en>\n"
	"<input type=hidden name=ie value=\"ISO-8859-1\">\n"
	"<input maxlength=2048 name=q size=55 title=\"Armitage Search\" value=\"\">\n"
	"<br>\n"
	"<input name=btnG type=submit value=\"Armitage Search\">\n"
	"<input name=btnI type=submit value=\"I'm Feeling Lucky\">\n"
	"</td>\n"
	"<td nowrap width=25%>\n"
	"<font size=-2>\n"
	"&nbsp;&nbsp;<a href=/advanced_search?hl=en>\n"
	"Advanced Search</a>\n"
	"<br>\n"
	"&nbsp;&nbsp;<a href=/preferences?hl=en>\n"
	"Preferences</a>\n"
	"<br>\n"
	"&nbsp;&nbsp;<a href=/language_tools?hl=en>\n"
	"Language Tools</a>\n"
	"</font>\n"
	"</td>\n"
	"</tr>\n"
	"<tr>\n"
	"<td align=center colspan=3>\n"
	"<font size=-1>\n"
	"<span style=\"text-align:left\">\n"
	"Search: <input id=all type=radio name=meta value=\"\" checked>\n"
	"<label for=all>\n"
	" the web </label>\n"
	"<input id=cty type=radio name=meta value=\"cr=countryUK|countryGB\">\n"
	"<label for=cty>\n"
	" pages from the UK </label>\n"
	"</span>\n"
	"</font>\n"
	"</td>\n"
	"</tr>\n"
	"</table>\n"
	"</form>\n"
	"<br>\n"
	"<br>\n"
	"<font size=-1>\n"
	"<a href=\"/Sebastian/\">\n"
	"Sebastian</a>\n"
	" - <a href=\"/Harriet/\">\n"
	"Harriet</a>\n"
	" - <a href=\"/Linda/\">\n"
	"Linda</a>\n"
	" - <a href=\"/Quentin/\">\n"
	"Quentin</a>\n"
	" - <a href=\"/Schools/\">\n"
	"Schools</a>\n"
	"</font>\n"
	"<p>\n"
	"<font size=-2>\n"
	"&copy;2011 Armitage</font>\n"
	"</p>\n"
	"</center>\n"
	"</body>\n"
	"</html>\n"
	"\n";
