#!/bin/sh
#
# Startup script for the Keepalived daemon
#
# processname: keepalived
# pidfile: /var/run/keepalived.pid
# config: /etc/keepalived/keepalived.conf

# See how we were called.
case "$1" in
  start)
	echo -n "Starting Keepalived for LVS: "
	keepalived
	echo
	;;
  stop)
	echo -n "Shutting down Keepalived for LVS: "
	PID=`ps ax | grep keepalived | awk '{print $1}'`
	kill $PID
	echo
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
