.TH KEEPALIVED "8" "November 2012"

.na
.nh

.SH "NAME"
keepalived \- load\-balancing and high\-availability service

.SH "SYNOPSIS"
\fBkeepalived\fP
[\fB\-f\fP|\fB\-\-use\-file\fP=FILE]
[\fB\-P\fP|\fB\-\-vrrp\fP]
[\fB\-C\fP|\fB\-\-check\fP]
[\fB\-l\fP|\fB\-\-log\-console\fP]
[\fB\-D\fP|\fB\-\-log\-detail\fP]
[\fB\-S\fP|\fB\-\-log\-facility\fP={0-7}]
[\fB\-V\fP|\fB\-\-dont\-release\-vrrp\fP]
[\fB\-I\fP|\fB\-\-dont\-release\-ipvs\fP]
[\fB\-R\fP|\fB\-\-dont\-respawn\fP]
[\fB\-n\fP|\fB\-\-dont\-fork\fP]
[\fB\-d\fP|\fB\-\-dump\-conf\fP]
[\fB\-p\fP|\fB\-\-pid\fP=FILE]
[\fB\-r\fP|\fB\-\-vrrp_pid\fP=FILE]
[\fB\-c\fP|\fB\-\-checkers_pid\fP=FILE]
[\fB\-x\fP|\fB\-\-snmp\fP]
[\fB\-A\fP|\fB\-\-snmp-agent-socket\fP=FILE]
[\fB\-v\fP|\fB\-\-version\fP]
[\fB\-h\fP|\fB\-\-help\fP]

.SH "DESCRIPTION"
Keepalived provides simple and robust facilities for load\-balancing
and high\-availability. The load\-balancing framework relies on
well\-known and widely used Linux Virtual Server (IPVS) kernel module
providing Layer4 load\-balancing. Keepalived implements a set of
checkers to dynamically and adaptively maintain and manage
load\-balanced server pool according their health. Keepalived also
implements the VRRPv2 protocol to achieve high\-availability with
director failover.

.SH "OPTIONS"
.TP
\fB -f, --use-file\fP=FILE
Use the specified configuration file. The default configuration file
is "/etc/keepalived/keepalived.conf".
.TP
\fB -P, --vrrp\fP
Only run the VRRP subsystem. This is useful for configurations that do
not use IPVS load balancer.
.TP
\fB -C, --check\fP
Only run the healthcheck subsystem. This is useful for configurations
that use the IPVS load balancer with a single director with no failover.
.TP
\fB -l, --log-console\fP
Log messages to the local console. The default behavior is to log
messages to syslog.
.TP
\fB -D, --log-detail\fP
Detailed log messages.
.TP
\fB -S, --log-facility\fP=[0-7]
Set syslog facility to LOG_LOCAL[0-7]. The default syslog facility is LOG_DAEMON.
.TP
\fB -V, --dont-release-vrrp\fP
Don't remove VRRP VIPs and VROUTEs on daemon stop. The default
behavior is to remove all VIPs and VROUTEs when keepalived exits
.TP
\fB -I, --dont-release-ipvs\fP
Don't remove IPVS topology on daemon stop. The default behavior it to
remove all entries from the IPVS virtual server table on when
keepalived exits.
.TP
\fB -R, --dont-respawn\fP
Don't respawn child processes. The default behavior is to restart the
VRRP and checker processes if either process exits.
.TP
\fB -n, --dont-fork\fP
Don't fork the daemon process. This option will cause keepalived to
run in the foreground.
.TP
\fB -d, --dump-conf\fP
Dump the configuration data.
.TP
\fB -p, --pid\fP=FILE
Use specified pidfile for parent keepalived process. The default
pidfile for keepalived is "/var/run/keepalived.pid".
.TP
\fB -r, --vrrp_pid\fP=FILE
Use specified pidfile for VRRP child process. The default pidfile for
the VRRP child process is "/var/run/keepalived_vrrp.pid".
.TP
\fB -c, --checkers_pid\fP=FILE
Use specified pidfile for checkers child process. The default pidfile
for the checker child process is "/var/run/keepalived_checkers.pid".
.TP
\fB -x, --snmp\fP
Enable SNMP subsystem.
.TP
\fB -A, --snmp-agent-socket\fP=FILE
Use the specified socket for connection to SNMP master agent.
.TP
\fB -v, --version\fP
Display the version and exit.
.TP
\fB -h, --help\fP
Display this help message and exit.

.SH "SEE ALSO"
\fBkeepalived.conf\fP(5), \fBipvsadm\fP(8)

.SH "AUTHOR"
This man page was written by Ryan O'Hara <rohara@redhat.com>
