#!/bin/bash

grep "#if" $(find . -name "*.[ch]") | \
	sed -e "s/&&/@/g" \
	    -e "s/||/@/g" \
	    -e "s/[<>]=*/@/g" \
	    -e "s/==/@/g" \
	    -e "s/[()]/@/g" \
	    -e "s/.*#if[a-z]*[ \t]*//" \
	    -e "s/defined/@/g" \
	    -e "s/\!//g" \
	    -e "s/^[ \t]*//" \
	    -e "s/[ \t]*\/\*.*\*\/[ \t]*//g" | \
	tr "@" "\n" | \
	sed -e "s/^[ \t]*//" \
	    -e "s/[ \t]*$//" \
	    -e "/^$/d" \
	    -e "/^[0-9,]*$/d" \
	    -e "/^0x[0-9A-Fa-f]*L+/d" | \
	sort | \
	uniq -c

