#!/bin/sh

if [ ! -f /etc/keepalived/keepalived.conf ]; then
  mkdir -p /etc/keepalived
  touch /etc/keepalived/keepalived.conf
fi

for file in /etc/dbus-1/system.d/org.keepalived.Vrrp1.conf /usr/share/dbus-1/interfaces/org.keepalived.Vrrp1.Instance.xml /usr/share/dbus-1/interfaces/org.keepalived.Vrrp1.Vrrp.xml; do
	[[ -d ${file%/*} ]] && cp -p $SNAP$file $file
done
